version: '3'

volumes:
  database_local:
  postgres_data:

services: 
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  mysite_local:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: mysite_local
    container_name: mysite_local
    working_dir: /app
    volumes:
      - database_local:/app/database
      - .:/app
    ports:
      - "8000:8000"
    command: /start.sh
    depends_on:
      - db
