version: '3'

volumes:
  static:
  database:
  postgres_data:

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  mysite:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: mysite
    container_name: mysite
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
      - "./entrypoint.sh:/entrypoint.sh"
    entrypoint: /entrypoint.sh -d db:5432 -c 'echo "start mysite service here"';
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: mysite_nginx
    container_name: mysite_nginx
    volumes:
      - static:/apps/mysite/static
      - "./entrypoint.sh:/entrypoint.sh"
    entrypoint: /entrypoint.sh -d mysite:8000 -c 'echo "start nginx service here"';
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysite

   