# Generated by Django 3.1.5 on 2021-03-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210314_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcount',
            name='count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
