# Generated by Django 3.1.5 on 2021-07-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210314_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='top_symbol',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
