# Generated by Django 3.1.5 on 2021-07-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210714_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcount',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
