# Generated by Django 3.1.5 on 2021-07-14 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210714_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, verbose_name='访问者IP')),
                ('view_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='访问时间')),
            ],
        ),
    ]
